### ISSUE TITLE
Allow any `AbstractArray`

### ISSUE THREAD

**Issue by zsunberg** [sisl/GaussianFilters.jl#14]
Wooohoo!! I am extremely excited about this package!! I have been hoping for a good EKF package that uses `ForwardDiff` for a while. This really does look like a great start! :) I think that I will get a lot of use out of it in classes I teach and research I do, and, if it's well-executed, I think it will be something that helps people transition from MATLAB to Julia.

Since I'm probably going to rely on this a lot, I am going to give a few suggestions - I hope they don't seem antagonistic; I just want to make sure the package is as good as possible!

The first suggestion is to allow the use of `AbstractArrays` everywhere. This will allow people to use their own, more efficient, array types. In particular, using [StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl) for small arrays can completely avoid the allocations that happen with built-in arrays and result in 10x or even 100x speedups.

This is very simple to support - for example `GaussianBelief` would look like this:
```julia
struct GaussianBelief{V<:AbstractVector,M<:AbstractMatrix}
    μ::V
    Σ::M
end
```

**Comment by jamgochiana** [comment]
Thanks for all the feedback. Array abstractions allowed in https://github.com/sisl/GaussianFilters.jl/commit/13b28f28cd5e30038994dd7ea20cce7a24e47ce4

**Comment by lassepe** [comment]
Just by grepping through the repo, I there are still quite a few non-abstract [`Vector`](https://github.com/sisl/GaussianFilters.jl/search?q=%3A%3AVector&unscoped_q=%3A%3AVector) and [`Matrix`](https://github.com/sisl/GaussianFilters.jl/search?q=%3A%3AMatrix&unscoped_q=%3A%3AMatrix). So this might need to be revisited.
