### ISSUE TITLE
Use Immutable Types

### ISSUE THREAD

**Issue by zsunberg** [sisl/GaussianFilters.jl#15]
[Suggestion (2) in the series started in #14]

Usually, when a mutable object is instantiated, [it allocates memory on the heap](https://docs.julialang.org/en/latest/manual/types/#Mutable-Composite-Types-1), which, in certain cases where caching is important, like inner loops or within Monte Carlo Tree Search, etc. can make them much slower. I think you could achieve significant speedup by making all of the types that you can immutable, especially things like `GaussianBelief` that are likely to be created and recreated often :)

**Comment by jamgochiana** [comment]
All structs fixed to immutable in https://github.com/sisl/GaussianFilters.jl/commit/78c1fbc99659b4d35d3ee25575d371588d23d293
