### ISSUE TITLE
Consistency of `update` with POMDPs.jl

### ISSUE THREAD

**Issue by zsunberg** [sisl/GaussianFilters.jl#17]
[Suggestion (4) of series starting in #14]

It would be really useful to make this interoperable with POMDPs.jl!! One thing that would help for that is consistency of the `update` function. Both `POMDPs.update` and `GaussianFilters.update` are very similar, except for the argument ordering:
```julia
POMDPs.update(filter, b, action, measurement)
GaussianFilters.update(b, action, measurement, filter)
```
We chose to put the filter first because it is the object that has the most "ownership" over the `update` function, i.e. the person who writes the filter type is most likely to write the corresponding `update` function. Would you consider switching the order of the arguments in this package to be consistent? That way people could easily switch between this and, for example, `ParticleFilters.jl`, and filters from this package could have plug and play compatibility with POMDPs.jl!! :)

**Comment by zsunberg** [comment]
Or perhaps there should be a `AbstractFilters.jl` package that `POMDPs.jl`, `GaussianFilters.jl`, and `ParticleFilters.jl` inherit from.

**Comment by jamgochiana** [comment]
Re-ordered filter function calls in https://github.com/sisl/GaussianFilters.jl/commit/dafa51275f186882a42ff3f7e25111423e10141a and https://github.com/sisl/GaussianFilters.jl/commit/2d4228981f5184bb335dd42f6638aece15528fe8
