### ISSUE TITLE
Return Innovation Covariance Matrices in Update Functions

### ISSUE THREAD

**Issue by jihodori** [sisl/GaussianFilters.jl#42]
Hi!

I am an MS student at CU Boulder working with Professor Zachary Sunberg. We recently wrote a paper on Rao-Blackwellized POMDPs (RB-POMDPs), which uses Gaussian filters for the linear state space. I used this package but had to modify some of the code because the current update functions do not return the innovation covariance matrices. I was wondering if I could help maintain this package. Professor Sunberg and I are working together to open-source our code so that others can easily use our model. Thank you in advance for your consideration!

Best,
Jiho

**Comment by zsunberg** [comment]
I just added @jihodori as a maintainer of this package so that he can work on it. I will help him learn how to maintain it in a sustainable way. Does anyone have any objections to him taking the lead on maintenance and improvements under my guidance?

**Comment by jihodori** [comment]
This is resolved by #43.
